[package]
name = "templating-engine"
version = "0.1.0"
authors = ["Aiden McClelland <aiden@start9.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_yaml = "0.8.11"
